version: '3.3'

services:
  wordpress:
    depends_on:
      - db
    build: .
    command: dev
    ports:
      - "8080:443"
    volumes:
      - ./wp/wp-content/themes/phila.gov-theme:/var/www/html/wp-content/themes/phila.gov-theme
      - /var/www/html/wp-content/themes/phila.gov-theme/node_modules
      - ssl-cert-persistence:/etc/ssl

      # Useful while developing the docker environment
      - ./scripts:/scripts
      - ./nginx:/etc/nginx
      - ./supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: philagov
      PHILA_PLUGINS_BUCKET: phila-wp-plugins-timwistest
      PHILA_MEDIA_BUCKET: phila-media-sync
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      DOMAIN: localhost:8080

  db:
    image: mysql:5.7
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
      - db-persistence:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: philagov

volumes:
  db-persistence:
  ssl-cert-persistence:
